enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "both"
version = "latest"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"
version = "latest"
included-patches = "'Theme' 'Hide video action buttons' 'Navigation buttons' 'Spoof app version' 'Disable auto captions' 'Premium heading' 'Change start page' 'Player flyout menu' 'External downloads' 'Copy video url' 'Seekbar tapping' 'Enable slide to seek' 'Remember video quality' 'Video ads' 'Hide ads' 'Minimized playback' 'Enable debugging' 'Open links externally' 'Bypass URL redirects' 'Remove tracking query parameter' 'Client spoof' 'GmsCore support' 'Spoof device dimensions' 'Announcements'"
exclusive-patches = true

