logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
included-patches = "'Tablet mini player' 'Navigation buttons' 'Spoof app version' 'Disable auto captions' 'Custom branding' 'Premium heading' 'Change start page' 'Custom player overlay opacity' 'External downloads' 'Copy video url' 'Seekbar tapping' 'Enable slide to seek' 'Remember video quality' 'Playback speed' 'Video ads' 'Hide ads' 'Minimized playback' 'Enable debugging' 'Open links externally' 'Bypass URL redirects' 'Always autorepeat' 'Remove tracking query parameter' 'Client spoof' 'GmsCore support' 'Spoof device dimensions' 'Announcements' 'Disable zoom haptics'"
exclusive-patches = true
